### PR TITLE
Split block types

### LINKED ISSUE #100: Datum fetch error with Shelley after Vasil support update
How to reproduce:
- up and run cardano-node with testnet
- execute ODC: `cabal run ogmios-datum-cache -- --db-connection "host=localhost port=5432 user=seabug dbname=seabug password=seabug" "--server-port" "9999" "--server-api" "usr:pwd" "--ogmios-address" "ogmios" "--ogmios-port" "1337" "--block-slot" "61645985" "--block-hash" "95e98d44866272d38c175716a2f8f1b4e17676a945746f70c36559218cd92adb" "--block-filter" "{\"address\": \"addr_test1wr05mmuhd3nvyjan9u4a7c76gj756am40qg7vuz90vnkjzczfulda\"}"`
- expected behaviour:
```
http GET localhost:9999/datum/15461b6a6be10f6cfccd3387ed43eb37fd5fbcdb9e91e3d7e8cedb2ef194fed1
HTTP/1.1 200 OK
Content-Type: application/json;charset=utf-8
Date: Tue, 28 Jun 2022 11:59:06 GMT
Server: Warp/3.3.17
Transfer-Encoding: chunked

{
    "constr": 0,
    "fields": [
        "ddf93a5c16387f8cd84f002207b3dd596c03a4bde3381dad5626a250",
        "bc95b779f98dd288858bffd0cdd3e53b796a83117ed15d6f2a4e90b67edb59df"
    ]
}
```

ogmios and cardano-node version: https://github.com/mlabs-haskell/seabug/pull/16

### PR DESCRIPTION
**Pull request by t4ccer**
Using one block type was a mistake, so I've split them back. Also closes #100

### CODE REVIEW

File: src/Block/Fetch.hs [hunk 1]
```diff
@@ -291,22 +291,10 @@ fetchNextBlock = do
...
-          <> type_
-          <> " raw: " -- TODO: raw output only on debug logging level
-          <> raw
-    Right (RollForward (MkNoDatumBlock type_ block) _tip) -> do
-      let block' = noDatum2datumBlock block
-      liftIO $ atomically $ writeTBQueue env.queue block'
-      logInfoNS "fetchNextBlock" $
-        "Fetched no datum " <> type_ <> " block: " <> Text.pack (show (block.slot, block.hash))
-    Right (RollForward (MkDatumBlock type_ block) _tip) -> do
+    Right (RollForward block _tip) -> do
```
Comment (ryukzak) [inline src/Block/Fetch.hs:294]: Maybe we need a more explicit error message in case we can't decode it upper?

**Review by ryukzak — APPROVED** [review]
Looks good, especially a set of `Some*` types, which is much simpler than typeclasses, which I do early.

File: src/Block/Fetch.hs (hunk 1 above)
Comment (ryukzak) [reply src/Block/Fetch.hs:294]: Yes, but if I don't mistake it will be a message like: `Left "Error in $: not enough input"` without any additional information, like the original message?
